---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: 5-demo
  namespace: flux-system
spec:
  interval: 10s
  ref:
    branch: 5-demo
  url: https://github.com/mcabrito/bb-app-source
