---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: 7-demo
  namespace: flux-system
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 7.7.-00bb2691
  secretRef:
    name: ghcr-auth
  url: oci://ghcr.io/mcabrito/bb-app