---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 4-demo
  namespace: flux-system
spec:
  interval: 10s
  path: ./app-740
  prune: true
  sourceRef:
    kind: Bucket
    name: minio-bucket
  targetNamespace: 4-demo
